#!/bin/bash
echo 'streamlink --twitch-disable-ads -p mpv twitch.tv/xqc 1080p60'
echo -n $"twitch.tv/"
read username
streamlink --twitch-disable-ads -p mpv "--twitch-api-header=Authorization=OAuth 9gv67dd45o3noztpsoxy7fcv9em03y" twitch.tv/$username 1080p60
