#!/bin/bash
echo 'streamlink --twitch-disable-ads -p mpv twitch.tv/xqc 1080p60'
echo -n $"twitch.tv/"
read username
streamlink --twitch-disable-ads --twitch-low-latency -p mpv -v twitch.tv/$username 1080p60
